[workspace]
members  = ["crates/*"]
resolver = "3"

[workspace.lints.clippy]
all      = "warn"
cargo    = "warn"
nursery  = "warn"
pedantic = "warn"

[profile.release]
codegen-units = 1
lto           = true
opt-level     = 3
