[package]
edition = "2024"
name    = "kem-rs"
version = "0.1.0"

[dependencies]
rand_core = "0.10.0"
sha3 = "0.10.8"
zeroize = { version = "1.8.2", features = ["derive"] }

[dev-dependencies]
aes = "0.8.4"
criterion = "0.8.2"
getrandom = { version = "0.4.1", features = ["sys_rng"] }
hex = "0.4.3"
rand_core = "0.10.0"
sha2 = "0.10.9"

[[bench]]
name = "mlkem"
harness = false
