[workspace]
members  = ["crates/*"]
resolver = "3"

[workspace.lints.clippy]
all      = { level = "warn", priority = -1 }
cargo    = { level = "warn", priority = -1 }
nursery  = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

cargo_common_metadata    = "allow"
cast_possible_truncation = "allow"

[profile.release]
codegen-units = 1
lto           = true
opt-level     = 3
